#!/usr/bin/env python3
"""
boundary/conditions.py
=======================

Generic boundary condition framework for the incompressible Navier-Stokes
finite volume solver. This module provides a comprehensive and extensible
set of boundary condition classes that can be applied to any face of a
two-dimensional structured mesh.

Theoretical background:
    In the finite volume method, boundary conditions are enforced through
    either Dirichlet (prescribed value) or Neumann (prescribed gradient)
    specification at the boundary faces. The choice of boundary condition
    dramatically affects the solution; hence, a physically consistent and
    numerically stable implementation is of paramount importance.

    The boundary conditions covered in this module are:

    1.  Wall (no-slip, slip, moving wall):
        - No-slip: u = 0, v = 0 (adherence condition for viscous flows).
        - Slip:    u·n = 0, ∂u_t/∂n = 0 (inviscid or free-slip).
        - Moving:  u = u_wall, v = v_wall (prescribed wall motion).

    2.  Inlet (fixed velocity, mass flow, turbulent profiles):
        - Fixed velocity:   u = u_in, v = v_in.
        - Mass flow:        ρu·A = m_dot.
        - Turbulent:        profiles from turbulent_inlet module.

    3.  Outlet (zero-gradient, convective):
        - Zero-gradient:    ∂φ/∂n = 0.
        - Convective:       ∂φ/∂t + U_conv·∂φ/∂n = 0.

    4.  Symmetry plane:
        - u·n = 0, ∂φ/∂n = 0 for all scalars.

    5.  Periodic:
        - φ(west) = φ(east), or φ(south) = φ(north).

    6.  Opening (pressure specified, velocity extrapolated):
        - p = p_specified, u extrapolated from interior.

References:
    - Ferziger, J. H. & Perić, M. (2002). Computational Methods for Fluid
      Dynamics, 3rd ed. Springer.
    - Versteeg, H. K. & Malalasekera, W. (2007). An Introduction to
      Computational Fluid Dynamics: The Finite Volume Method, 2nd ed.
      Pearson Education.
    - Patankar, S. V. (1980). Numerical Heat Transfer and Fluid Flow.
      Hemisphere Publishing Corporation.

Author:     Ananya Patel
            Indian Institute of Technology Bombay
Date:       2026-07-27
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import IntEnum
from typing import Callable, Optional, Union

import numpy as np

from navier_stokes import (
    BoundaryCondition,
    Field2D,
    Mesh2D,
)

# ─── Type aliases for improved readability ─────────────────────────────
# Please note that these aliases are provided solely for the convenience
# of the user and do not alter the underlying type semantics.
VelocityProfile = Callable[[np.ndarray, np.ndarray], np.ndarray]
"""
A callable that accepts coordinate arrays (x, y) and returns a velocity
magnitude array of the same shape. This is useful for specifying spatially
varying inlet profiles.
"""


# ─── Custom boundary condition type enum ───────────────────────────────
# It is crucial to understand that the base `BoundaryCondition` enum in
# `navier_stokes` provides only the fundamental types. We extend the
# classification here with sub-types that capture additional physical detail.

class WallType(IntEnum):
    """Enumeration of wall boundary condition sub-types.

    Please note that each sub-type corresponds to a different physical
    model of the fluid-solid interface.

    Attributes:
        NO_SLIP:  The fluid velocity at the wall is identically zero
                  relative to the wall (u = u_wall). This is the most
                  common treatment for viscous flows.
        SLIP:     The wall-normal velocity is zero, but the tangential
                  component is free (∂u_t/∂n = 0). This is appropriate
                  for inviscid flows or symmetry-like solid boundaries.
        MOVING:   The wall has a prescribed non-zero velocity. The fluid
                  adheres to the wall (no-slip condition applied in the
                  moving reference frame).
    """
    NO_SLIP = 0
    SLIP = 1
    MOVING = 2


class InletType(IntEnum):
    """Enumeration of inlet boundary condition sub-types.

    Attributes:
        FIXED_VELOCITY:  Direct specification of the velocity vector
                         at the inlet face.
        MASS_FLOW:       Specification of the mass flow rate; the
                         velocity is computed as m_dot / (ρ · A).
        TURBULENT:       Turbulent velocity profile generated by one
                         of the methods in `turbulent_inlet.py`.
    """
    FIXED_VELOCITY = 0
    MASS_FLOW = 1
    TURBULENT = 2


class OutletType(IntEnum):
    """Enumeration of outlet boundary condition sub-types.

    Attributes:
        ZERO_GRADIENT:  The normal derivative of all transported
                        quantities is set to zero (∂φ/∂n = 0).
        CONVECTIVE:     A convective boundary condition that allows
                        vortical structures to exit the domain with
                        minimal reflection.
    """
    ZERO_GRADIENT = 0
    CONVECTIVE = 1


# ─── Base class ────────────────────────────────────────────────────────

@dataclass
class _BoundaryBase:
    """Base class for all boundary condition implementations.

    This class provides common attributes and validation logic that are
    shared across all boundary condition types. Kindly ensure that the
    mesh object passed to any derived class is fully initialised before
    use.

    Attributes:
        mesh:       The 2D computational mesh on which the boundary
                    condition is to be applied.
        side:       A string indicating which side of the domain this
                    boundary condition applies to. Must be one of
                    'west', 'east', 'south', or 'north'.
    """
    mesh: Mesh2D
    side: str = "west"

    def __post_init__(self) -> None:
        """Validates the `side` parameter upon initialisation.

        Raises:
            ValueError: If `side` is not one of the four cardinal
                        directions recognised by the solver.
        """
        # It is crucial to understand that the side identifier must match
        # exactly what the SIMPLE solver expects in its boundary condition
        # application routine.
        valid_sides: set[str] = {"west", "east", "south", "north"}
        if self.side not in valid_sides:
            raise ValueError(
                f"Boundary side '{self.side}' is not valid. "
                f"Kindly ensure that the side is one of {valid_sides}."
            )

    def _face_indices(self) -> tuple[int, slice, int, int]:
        """Returns the index range corresponding to the boundary face.

        This method translates the string-based side identifier into
        concrete array indices that can be used to slice the field arrays.

        Returns:
            A tuple (i_face, j_slice, normal_sign, n_cells_along_face)
            where:
                i_face:         The i-index of the boundary face row/column.
                j_slice:        The j-slice (or i-slice) for selecting cells.
                normal_sign:    +1 if the outward normal points in the
                                positive coordinate direction, -1 otherwise.
                n_cells_along_face: Number of cells along this boundary.
        """
        nx: int = self.mesh.nx
        ny: int = self.mesh.ny

        if self.side == "west":
            # West face: i = 0, all j
            return 0, slice(None, None), -1, ny
        elif self.side == "east":
            # East face: i = nx - 1, all j
            return nx - 1, slice(None, None), +1, ny
        elif self.side == "south":
            # South face: j = 0, all i
            return 0, slice(None, None), -1, nx
        elif self.side == "north":
            # North face: j = ny - 1, all i
            return ny - 1, slice(None, None), +1, nx
        else:
            # This branch should never be reached if __post_init__ passed.
            raise ValueError(f"Unrecognised side: {self.side}")


# ─── Wall boundary condition ───────────────────────────────────────────

@dataclass
class Wall:
    """Wall boundary condition with support for no-slip, slip, and moving
    wall treatments.

    Physical background:
        The wall boundary condition represents the interface between a
        fluid domain and a solid surface. For viscous fluids, the no-slip
        condition dictates that the fluid velocity at the wall equals the
        velocity of the wall itself. This arises from the molecular
        interaction between the fluid and the solid surface. For inviscid
        or high-Reynolds-number simulations where the viscous sublayer is
        not resolved, a slip condition may be employed instead.

    Please note that the moving wall capability is essential for problems
    such as lid-driven cavity flow, rotating machinery, and moving
    boundaries in fluid-structure interaction.

    Args:
        wall_type:  The type of wall condition (NO_SLIP, SLIP, MOVING).
                    Defaults to NO_SLIP.
        u_wall:     The x-component of the wall velocity. Only used when
                    wall_type is MOVING. Defaults to 0.0.
        v_wall:     The y-component of the wall velocity. Only used when
                    wall_type is MOVING. Defaults to 0.0.
    """
    wall_type: WallType = WallType.NO_SLIP
    u_wall: float = 0.0
    v_wall: float = 0.0

    def apply(
        self,
        u: Field2D,
        v: Field2D,
        mesh: Mesh2D,
        side: str,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Applies the wall boundary condition to the velocity field along
        the specified side of the domain.

        This method modifies the velocity field arrays in-place on the
        boundary cells. Kindly ensure that the velocity fields have been
        properly initialised before calling this method.

        Args:
            u:      The x-velocity field (nx × ny).
            v:      The y-velocity field (nx × ny).
            mesh:   The computational mesh.
            side:   The side on which to apply the condition ('west',
                    'east', 'south', or 'north').

        Returns:
            A tuple (u, v) with the boundary values updated.

        Raises:
            ValueError: If `side` is not recognised.
        """
        # ── Determine the correct slice indices based on side ──────────
        nx: int = mesh.nx
        ny: int = mesh.ny

        if side == "west":
            # West boundary: i = 0
            if self.wall_type == WallType.NO_SLIP:
                # For no-slip, both velocity components are set to the
                # wall velocity (which is zero by default).
                u.data[0, :] = self.u_wall
                v.data[0, :] = self.v_wall
            elif self.wall_type == WallType.SLIP:
                # For slip, the wall-normal velocity (u on west face)
                # is zero, and the tangential component (v) is
                # extrapolated from the interior (zero-gradient).
                u.data[0, :] = 0.0
                v.data[0, :] = v.data[1, :]
            elif self.wall_type == WallType.MOVING:
                # Moving wall: fluid adheres to the wall motion.
                u.data[0, :] = self.u_wall
                v.data[0, :] = self.v_wall
            else:
                # Defensive check: all enum values should be covered.
                raise ValueError(f"Unsupported WallType: {self.wall_type}")

        elif side == "east":
            # East boundary: i = nx - 1
            if self.wall_type == WallType.NO_SLIP:
                u.data[-1, :] = self.u_wall
                v.data[-1, :] = self.v_wall
            elif self.wall_type == WallType.SLIP:
                u.data[-1, :] = 0.0
                v.data[-1, :] = v.data[-2, :]
            elif self.wall_type == WallType.MOVING:
                u.data[-1, :] = self.u_wall
                v.data[-1, :] = self.v_wall
            else:
                raise ValueError(f"Unsupported WallType: {self.wall_type}")

        elif side == "south":
            # South boundary: j = 0
            if self.wall_type == WallType.NO_SLIP:
                u.data[:, 0] = self.u_wall
                v.data[:, 0] = self.v_wall
            elif self.wall_type == WallType.SLIP:
                # For south wall, the normal velocity is v, so set to zero.
                u.data[:, 0] = u.data[:, 1]
                v.data[:, 0] = 0.0
            elif self.wall_type == WallType.MOVING:
                u.data[:, 0] = self.u_wall
                v.data[:, 0] = self.v_wall
            else:
                raise ValueError(f"Unsupported WallType: {self.wall_type}")

        elif side == "north":
            # North boundary: j = ny - 1
            if self.wall_type == WallType.NO_SLIP:
                u.data[:, -1] = self.u_wall
                v.data[:, -1] = self.v_wall
            elif self.wall_type == WallType.SLIP:
                u.data[:, -1] = u.data[:, -2]
                v.data[:, -1] = 0.0
            elif self.wall_type == WallType.MOVING:
                u.data[:, -1] = self.u_wall
                v.data[:, -1] = self.v_wall
            else:
                raise ValueError(f"Unsupported WallType: {self.wall_type}")

        else:
            # This branch catches any side that is not one of the four
            # recognised cardinal directions.
            raise ValueError(
                f"Side '{side}' is not recognised. "
                f"Kindly ensure that the side is 'west', 'east', "
                f"'south', or 'north'."
            )

        return u.data, v.data

    def apply_pressure(
        self,
        p: Field2D,
        mesh: Mesh2D,
        side: str,
    ) -> np.ndarray:
        """Applies the pressure boundary condition at a wall.

        At a solid wall, the pressure boundary condition is typically
        zero-gradient (∂p/∂n = 0), which is consistent with the
        pressure correction equation in the SIMPLE algorithm.

        Args:
            p:      The pressure field (nx × ny).
            mesh:   The computational mesh.
            side:   The side on which to apply the condition.

        Returns:
            The modified pressure field array.
        """
        nx: int = mesh.nx
        ny: int = mesh.ny

        if side == "west":
            # Zero-gradient: set boundary pressure equal to adjacent
            # interior cell value.
            p.data[0, :] = p.data[1, :]
        elif side == "east":
            p.data[-1, :] = p.data[-2, :]
        elif side == "south":
            p.data[:, 0] = p.data[:, 1]
        elif side == "north":
            p.data[:, -1] = p.data[:, -2]
        else:
            raise ValueError(f"Unrecognised side: {side}")

        return p.data


# ─── Inlet boundary condition ──────────────────────────────────────────

@dataclass
class Inlet:
    """Inlet boundary condition with support for fixed velocity, mass flow,
    and turbulent profile specifications.

    Physical background:
        The inlet boundary condition specifies the flow properties at the
        domain entrance. For incompressible flows, the velocity distribution
        at the inlet has a profound influence on the downstream development
        of the flow. A uniform profile is the simplest choice, but parabolic
        (fully-developed) or turbulent profiles are often more physically
        realistic.

    Please note that when using the MASS_FLOW type, the cross-sectional
    area is computed automatically from the mesh geometry, and the density
    must be provided. Kindly ensure that the mass flow rate is consistent
    with the desired Reynolds number.

    Args:
        inlet_type:      The type of inlet specification (FIXED_VELOCITY,
                         MASS_FLOW, or TURBULENT).
        u_in:            Prescribed x-velocity at the inlet. Used for
                         FIXED_VELOCITY. Defaults to 1.0.
        v_in:            Prescribed y-velocity at the inlet. Defaults to 0.0.
        mass_flow_rate:  Mass flow rate in kg/s. Used for MASS_FLOW.
                         Defaults to 1.0.
        density:         Fluid density in kg/m³. Used for MASS_FLOW.
                         Defaults to 1.0.
        profile_fn:      A callable that returns a velocity profile array.
                         Used for TURBULENT type. The callable should
                         accept (x_coords, y_coords) and return velocity
                         magnitudes. Defaults to None (uniform profile).
    """
    inlet_type: InletType = InletType.FIXED_VELOCITY
    u_in: float = 1.0
    v_in: float = 0.0
    mass_flow_rate: float = 1.0
    density: float = 1.0
    profile_fn: Optional[VelocityProfile] = None

    def apply(
        self,
        u: Field2D,
        v: Field2D,
        mesh: Mesh2D,
        side: str,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Applies the inlet boundary condition to the velocity field along
        the specified side.

        This method computes the appropriate velocity values at the inlet
        boundary based on the selected inlet type and assigns them to the
        boundary cells.

        Args:
            u:      The x-velocity field (nx × ny).
            v:      The y-velocity field (nx × ny).
            mesh:   The computational mesh.
            side:   The side on which to apply the condition.

        Returns:
            A tuple (u, v) with the inlet boundary values set.

        Raises:
            ValueError: If the inlet type is not recognised or if the
                        side specification is invalid.
        """
        nx: int = mesh.nx
        ny: int = mesh.ny
        u_arr: np.ndarray = u.data
        v_arr: np.ndarray = v.data

        # ── Determine the face area and coordinate array ───────────────
        # It is crucial to understand that the cross-sectional area depends
        # on the orientation of the inlet face.
        if side in ("west", "east"):
            # For east/west faces, the face area is dy (per unit depth).
            face_normal: float = mesh.dy
            # Coordinates along the inlet face (y direction).
            face_coords: np.ndarray = mesh.yc
        elif side in ("south", "north"):
            face_normal = mesh.dx
            face_coords = mesh.xc
        else:
            raise ValueError(f"Invalid side: {side}")

        # ── Compute the velocity magnitude at the inlet ────────────────
        if self.inlet_type == InletType.FIXED_VELOCITY:
            # Direct velocity specification. This is the simplest and most
            # commonly used form of inlet boundary condition.
            u_magnitude: float = self.u_in
            v_magnitude: float = self.v_in

        elif self.inlet_type == InletType.MASS_FLOW:
            # Mass flow specification: u = m_dot / (ρ · A).
            # The velocity is uniform across the inlet face.
            # Please note that the cross-sectional area A is computed as
            # the product of the face normal distance and the depth
            # (assumed to be unity for 2D simulations).
            cross_sectional_area: float = face_normal * 1.0  # depth = 1
            if cross_sectional_area <= 0.0:
                raise ValueError(
                    "The cross-sectional area at the inlet must be "
                    "positive. Kindly check the mesh dimensions."
                )
            # Compute the uniform velocity magnitude from mass flow rate.
            u_magnitude = self.mass_flow_rate / (self.density * cross_sectional_area)
            v_magnitude = 0.0

        elif self.inlet_type == InletType.TURBULENT:
            # Turbulent profile specified by a user-provided callable.
            if self.profile_fn is not None:
                # Generate the velocity profile using the provided function.
                # The function receives the coordinates along the face and
                # returns the corresponding velocity magnitudes.
                profile: np.ndarray = self.profile_fn(face_coords, np.zeros_like(face_coords))
                # The profile may be a scalar or an array; ensure it is
                # properly shaped.
                if np.isscalar(profile):
                    u_magnitude = float(profile)
                else:
                    u_magnitude = profile
            else:
                # Fall back to uniform velocity if no profile function is
                # provided. This ensures that the code does not crash,
                # though the user is strongly encouraged to provide a
                # physically meaningful profile.
                u_magnitude = self.u_in
            v_magnitude = self.v_in

        else:
            raise ValueError(
                f"InletType '{self.inlet_type}' is not supported. "
                f"Kindly select from FIXED_VELOCITY, MASS_FLOW, or "
                f"TURBULENT."
            )

        # ── Assign the velocity values to the boundary cells ───────────
        # The assignment depends on the orientation of the boundary face.
        if side == "west":
            # West face: flow enters in the +x direction.
            if isinstance(u_magnitude, np.ndarray):
                u_arr[0, :] = u_magnitude
            else:
                u_arr[0, :] = u_magnitude
            v_arr[0, :] = v_magnitude
        elif side == "east":
            # East face: flow enters in the -x direction (unusual but
            # permitted for bidirectional flows).
            if isinstance(u_magnitude, np.ndarray):
                u_arr[-1, :] = -u_magnitude
            else:
                u_arr[-1, :] = -u_magnitude
            v_arr[-1, :] = v_magnitude
        elif side == "south":
            # South face: flow enters in the +y direction.
            u_arr[:, 0] = u_magnitude
            if isinstance(v_magnitude, np.ndarray):
                v_arr[:, 0] = v_magnitude
            else:
                v_arr[:, 0] = v_magnitude
        elif side == "north":
            # North face: flow enters in the -y direction.
            u_arr[:, -1] = u_magnitude
            if isinstance(v_magnitude, np.ndarray):
                v_arr[:, -1] = -v_magnitude
            else:
                v_arr[:, -1] = -v_magnitude
        else:
            raise ValueError(f"Invalid side: {side}")

        return u_arr, v_arr

    def apply_pressure(
        self,
        p: Field2D,
        mesh: Mesh2D,
        side: str,
    ) -> np.ndarray:
        """Applies the pressure boundary condition at an inlet.

        At an inlet, the pressure is typically extrapolated from the
        interior using a zero-gradient condition, unless the pressure
        is specifically prescribed.

        Args:
            p:      The pressure field (nx × ny).
            mesh:   The computational mesh.
            side:   The side on which to apply the condition.

        Returns:
            The modified pressure field array.
        """
        p_arr: np.ndarray = p.data
        nx: int = mesh.nx
        ny: int = mesh.ny

        if side == "west":
            p_arr[0, :] = p_arr[1, :]
        elif side == "east":
            p_arr[-1, :] = p_arr[-2, :]
        elif side == "south":
            p_arr[:, 0] = p_arr[:, 1]
        elif side == "north":
            p_arr[:, -1] = p_arr[:, -2]
        else:
            raise ValueError(f"Invalid side: {side}")

        return p_arr


# ─── Outlet boundary condition ─────────────────────────────────────────

@dataclass
class Outlet:
    """Outlet boundary condition with zero-gradient and convective options.

    Physical background:
        The outlet boundary condition is applied at flow exit boundaries
        where the flow leaves the computational domain. The zero-gradient
        condition (∂φ/∂n = 0) is the most common choice and assumes that
        the flow is fully developed at the exit. However, for unsteady
        flows with passing vortices, a convective boundary condition is
        preferred as it allows structures to advect out of the domain with
        minimal spurious reflection.

    The convective boundary condition is given by:
        ∂φ/∂t + U_conv · ∂φ/∂n = 0

    where U_conv is a specified convection velocity, typically taken as
    the bulk mean velocity at the outlet.

    References:
        - Orlanski, I. (1976). A simple boundary condition for unbounded
          hyperbolic flows. Journal of Computational Physics, 21(3):251-269.

    Args:
        outlet_type:       The type of outlet condition (ZERO_GRADIENT or
                           CONVECTIVE).
        conv_velocity:     The convection velocity for the CONVECTIVE type.
                           Defaults to 1.0. It is crucial to understand that
                           this should be approximately the bulk velocity
                           at the outlet for best results.
        dt:                The time step size. Required for CONVECTIVE type.
                           Defaults to 0.01.
    """
    outlet_type: OutletType = OutletType.ZERO_GRADIENT
    conv_velocity: float = 1.0
    dt: float = 0.01

    def apply(
        self,
        u: Field2D,
        v: Field2D,
        mesh: Mesh2D,
        side: str,
        u_old: Optional[Field2D] = None,
        v_old: Optional[Field2D] = None,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Applies the outlet boundary condition to the velocity field.

        Args:
            u:      The x-velocity field (nx × ny) at the current time.
            v:      The y-velocity field (nx × ny) at the current time.
            mesh:   The computational mesh.
            side:   The side on which to apply the condition.
            u_old:  The x-velocity field at the previous time step.
                    Required for CONVECTIVE type. Defaults to None.
            v_old:  The y-velocity field at the previous time step.
                    Required for CONVECTIVE type. Defaults to None.

        Returns:
            A tuple (u, v) with the outlet boundary values updated.

        Raises:
            ValueError: If the outlet type or side is not recognised.
        """
        u_arr: np.ndarray = u.data
        v_arr: np.ndarray = v.data
        nx: int = mesh.nx
        ny: int = mesh.ny

        if self.outlet_type == OutletType.ZERO_GRADIENT:
            # ── Zero-gradient condition: ∂φ/∂n = 0 ─────────────────
            # This is implemented by setting the boundary cell value equal
            # to the adjacent interior cell value. This is a first-order
            # accurate implementation; higher-order extrapolation can be
            # added if needed.
            if side == "west":
                u_arr[0, :] = u_arr[1, :]
                v_arr[0, :] = v_arr[1, :]
            elif side == "east":
                u_arr[-1, :] = u_arr[-2, :]
                v_arr[-1, :] = v_arr[-2, :]
            elif side == "south":
                u_arr[:, 0] = u_arr[:, 1]
                v_arr[:, 0] = v_arr[:, 1]
            elif side == "north":
                u_arr[:, -1] = u_arr[:, -2]
                v_arr[:, -1] = v_arr[:, -2]
            else:
                raise ValueError(f"Invalid side: {side}")

        elif self.outlet_type == OutletType.CONVECTIVE:
            # ── Convective condition: ∂φ/∂t + U_conv · ∂φ/∂n = 0 ──
            # Please note that this requires the previous time step
            # velocity fields.
            if u_old is None or v_old is None:
                raise ValueError(
                    "The convective outlet condition requires the "
                    "velocity fields from the previous time step "
                    "(u_old and v_old). Kindly provide these arrays."
                )

            # Compute the spatial derivative using one-sided differences.
            # It is crucial to understand that the sign of the convection
            # velocity determines the direction of information propagation.
            if side == "west":
                # Outlet at west: flow exits in the -x direction.
                dudn = (u_arr[1, :] - u_arr[0, :]) / mesh.dx
                dvdn = (v_arr[1, :] - v_arr[0, :]) / mesh.dx
                u_arr[0, :] = u_old.data[0, :] - self.conv_velocity * self.dt * dudn
                v_arr[0, :] = v_old.data[0, :] - self.conv_velocity * self.dt * dvdn
            elif side == "east":
                # Outlet at east: flow exits in the +x direction.
                dudn = (u_arr[-1, :] - u_arr[-2, :]) / mesh.dx
                dvdn = (v_arr[-1, :] - v_arr[-2, :]) / mesh.dx
                u_arr[-1, :] = u_old.data[-1, :] - self.conv_velocity * self.dt * dudn
                v_arr[-1, :] = v_old.data[-1, :] - self.conv_velocity * self.dt * dvdn
            elif side == "south":
                # Outlet at south: flow exits in the -y direction.
                dudn = (u_arr[:, 1] - u_arr[:, 0]) / mesh.dy
                dvdn = (v_arr[:, 1] - v_arr[:, 0]) / mesh.dy
                u_arr[:, 0] = u_old.data[:, 0] - self.conv_velocity * self.dt * dudn
                v_arr[:, 0] = v_old.data[:, 0] - self.conv_velocity * self.dt * dvdn
            elif side == "north":
                # Outlet at north: flow exits in the +y direction.
                dudn = (u_arr[:, -1] - u_arr[:, -2]) / mesh.dy
                dvdn = (v_arr[:, -1] - v_arr[:, -2]) / mesh.dy
                u_arr[:, -1] = u_old.data[:, -1] - self.conv_velocity * self.dt * dudn
                v_arr[:, -1] = v_old.data[:, -1] - self.conv_velocity * self.dt * dvdn
            else:
                raise ValueError(f"Invalid side: {side}")

        else:
            raise ValueError(
                f"OutletType '{self.outlet_type}' is not supported. "
                f"Kindly select ZERO_GRADIENT or CONVECTIVE."
            )

        return u_arr, v_arr

    def apply_pressure(
        self,
        p: Field2D,
        mesh: Mesh2D,
        side: str,
    ) -> np.ndarray:
        """Applies the pressure boundary condition at an outlet.

        At an outlet, the pressure is typically prescribed as zero or a
        fixed value. In the SIMPLE algorithm, the outlet pressure correction
        is set to zero.

        Args:
            p:      The pressure field (nx × ny).
            mesh:   The computational mesh.
            side:   The side on which to apply the condition.

        Returns:
            The modified pressure field array.
        """
        p_arr: np.ndarray = p.data

        # For outlet boundaries, the pressure is set to zero (gauge
        # pressure). If a non-zero back pressure is desired, it should
        # be added after the correction step.
        if side == "west":
            p_arr[0, :] = 0.0
        elif side == "east":
            p_arr[-1, :] = 0.0
        elif side == "south":
            p_arr[:, 0] = 0.0
        elif side == "north":
            p_arr[:, -1] = 0.0
        else:
            raise ValueError(f"Invalid side: {side}")

        return p_arr


# ─── Symmetry plane boundary condition ─────────────────────────────────

@dataclass
class SymmetryPlane:
    """Symmetry plane boundary condition.

    Physical background:
        A symmetry plane boundary condition is used when the flow field
        exhibits mirror symmetry about a plane. The conditions are:
            - The velocity component normal to the symmetry plane is zero
              (u·n = 0, no penetration).
            - The normal derivative of all scalar quantities and tangential
              velocity components is zero (∂φ/∂n = 0).

        This boundary condition is computationally efficient as it reduces
        the domain size by a factor of two when symmetry exists. However,
        it is crucial to understand that this condition is only physically
        valid when the mean flow and geometry are truly symmetric.

    Please note that using a symmetry plane for turbulent flows requires
    that the turbulent structures are also symmetric, which is rarely the
    case for instantaneous fields.
    """

    def apply(
        self,
        u: Field2D,
        v: Field2D,
        mesh: Mesh2D,
        side: str,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Applies the symmetry plane condition to the velocity field.

        Args:
            u:      The x-velocity field (nx × ny).
            v:      The y-velocity field (nx × ny).
            mesh:   The computational mesh.
            side:   The side on which to apply the condition.

        Returns:
            A tuple (u, v) with the symmetry boundary values set.
        """
        u_arr: np.ndarray = u.data
        v_arr: np.ndarray = v.data

        if side == "west":
            # West symmetry: u (normal component) = 0, v (tangential) ∂/∂n = 0
            u_arr[0, :] = 0.0
            v_arr[0, :] = v_arr[1, :]
        elif side == "east":
            # East symmetry: u (normal) = 0
            u_arr[-1, :] = 0.0
            v_arr[-1, :] = v_arr[-2, :]
        elif side == "south":
            # South symmetry: v (normal) = 0
            u_arr[:, 0] = u_arr[:, 1]
            v_arr[:, 0] = 0.0
        elif side == "north":
            # North symmetry: v (normal) = 0
            u_arr[:, -1] = u_arr[:, -2]
            v_arr[:, -1] = 0.0
        else:
            raise ValueError(f"Invalid side: {side}")

        return u_arr, v_arr

    def apply_pressure(
        self,
        p: Field2D,
        mesh: Mesh2D,
        side: str,
    ) -> np.ndarray:
        """Applies the symmetry plane condition to the pressure field.

        At a symmetry plane, the normal derivative of pressure is zero.

        Args:
            p:      The pressure field (nx × ny).
            mesh:   The computational mesh.
            side:   The side on which to apply the condition.

        Returns:
            The modified pressure field array.
        """
        p_arr: np.ndarray = p.data

        # Zero-gradient condition for pressure at symmetry plane.
        if side == "west":
            p_arr[0, :] = p_arr[1, :]
        elif side == "east":
            p_arr[-1, :] = p_arr[-2, :]
        elif side == "south":
            p_arr[:, 0] = p_arr[:, 1]
        elif side == "north":
            p_arr[:, -1] = p_arr[:, -2]
        else:
            raise ValueError(f"Invalid side: {side}")

        return p_arr


# ─── Periodic boundary condition ───────────────────────────────────────

@dataclass
class Periodic:
    """Periodic boundary condition for pairs of opposing domain faces.

    Physical background:
        Periodic boundary conditions are used when the flow geometry and
        physics are repetitive in space. The condition enforces that the
        flow variables at one boundary are identical to those at the
        opposite boundary. This is commonly used for:

        - Streamwise-periodic flows (fully-developed channel/pipe flow).
        - Spanwise-homogeneous directions in turbulent simulations.
        - Array of identical geometries (e.g., heat exchanger tubes).

    Mathematically:
        φ(x_west) = φ(x_east)   and   φ(x_south) = φ(x_north)

    It is crucial to understand that for periodic boundaries, the mesh
    spacing must be consistent across the paired faces.

    Args:
        paired_side: The side that this periodic boundary is paired with.
                     For example, if `side='west'`, then `paired_side`
                     should be 'east', and vice versa.
        pressure_gradient: A constant pressure gradient (∂p/∂x) that drives
                           the flow in periodic domains. This is commonly
                           used for fully-developed channel flow where the
                           pressure drop is specified instead of the
                           velocity. Defaults to 0.0.
    """
    paired_side: str = ""
    pressure_gradient: float = 0.0

    def apply(
        self,
        u: Field2D,
        v: Field2D,
        mesh: Mesh2D,
        side: str,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Applies the periodic boundary condition to the velocity field.

        Args:
            u:      The x-velocity field (nx × ny).
            v:      The y-velocity field (nx × ny).
            mesh:   The computational mesh.
            side:   The side on which to apply the condition.

        Returns:
            A tuple (u, v) with the periodic boundary values set.
        """
        u_arr: np.ndarray = u.data
        v_arr: np.ndarray = v.data

        # It is crucial to understand that if the paired_side is not
        # explicitly set, we infer it automatically from the current side.
        if not self.paired_side:
            # Automatic pairing based on the current side.
            if side == "west":
                self.paired_side = "east"
            elif side == "east":
                self.paired_side = "west"
            elif side == "south":
                self.paired_side = "north"
            elif side == "north":
                self.paired_side = "south"
            else:
                raise ValueError(f"Invalid side: {side}")

        # Apply periodic condition: the value at this boundary is set
        # equal to the value at the paired boundary.
        if side == "west" and self.paired_side == "east":
            # West face gets the value from the east face interior cell.
            u_arr[0, :] = u_arr[-2, :]
            v_arr[0, :] = v_arr[-2, :]
        elif side == "east" and self.paired_side == "west":
            # East face gets the value from the west face interior cell.
            u_arr[-1, :] = u_arr[1, :]
            v_arr[-1, :] = v_arr[1, :]
        elif side == "south" and self.paired_side == "north":
            # South face gets the value from the north face interior cell.
            u_arr[:, 0] = u_arr[:, -2]
            v_arr[:, 0] = v_arr[:, -2]
        elif side == "north" and self.paired_side == "south":
            # North face gets the value from the south face interior cell.
            u_arr[:, -1] = u_arr[:, 1]
            v_arr[:, -1] = v_arr[:, 1]
        else:
            raise ValueError(
                f"The pairing ({side} ↔ {self.paired_side}) is not "
                f"consistent. Kindly ensure that opposing sides are "
                f"paired correctly (west↔east, south↔north)."
            )

        return u_arr, v_arr

    def apply_pressure(
        self,
        p: Field2D,
        mesh: Mesh2D,
        side: str,
    ) -> np.ndarray:
        """Applies the periodic boundary condition to the pressure field.

        For periodic boundaries, the pressure is also periodic. If a
        constant pressure gradient is specified, it is added to the
        periodic component.

        Args:
            p:      The pressure field (nx × ny).
            mesh:   The computational mesh.
            side:   The side on which to apply the condition.

        Returns:
            The modified pressure field array.
        """
        p_arr: np.ndarray = p.data

        # Automatically infer paired side if not set.
        if not self.paired_side:
            if side == "west":
                self.paired_side = "east"
            elif side == "east":
                self.paired_side = "west"
            elif side == "south":
                self.paired_side = "north"
            elif side == "north":
                self.paired_side = "south"

        # Apply periodic pressure condition.
        if side == "west" and self.paired_side == "east":
            p_arr[0, :] = p_arr[-2, :]
        elif side == "east" and self.paired_side == "west":
            p_arr[-1, :] = p_arr[1, :]
        elif side == "south" and self.paired_side == "north":
            p_arr[:, 0] = p_arr[:, -2]
        elif side == "north" and self.paired_side == "south":
            p_arr[:, -1] = p_arr[:, 1]

        # Apply the mean pressure gradient if specified.
        # This adds a constant driving force throughout the domain.
        if self.pressure_gradient != 0.0:
            if side == "west":
                p_arr[0, :] -= self.pressure_gradient * mesh.lx
            elif side == "east":
                p_arr[-1, :] -= self.pressure_gradient * mesh.lx

        return p_arr


# ─── Opening boundary condition ────────────────────────────────────────

@dataclass
class Opening:
    """Opening (pressure-specified) boundary condition.

    Physical background:
        The opening boundary condition is used when the flow may enter or
        exit the domain depending on the local pressure field. This is
        common in natural convection, ventilation, and internal flows
        where the direction of flow at the boundary is not known a priori.

    The treatment is:
        - Pressure is prescribed at the opening (Dirichlet for p).
        - Velocity is extrapolated from the interior (Neumann for u, v).
        - If the computed normal velocity is directed into the domain
          (inflow), the tangential velocity components may need special
          treatment.

    It is crucial to understand that the opening condition is distinct from
    a simple inlet or outlet because the flow direction is determined as
    part of the solution.

    Args:
        p_opening:  The prescribed gauge pressure at the opening.
                    Defaults to 0.0.
    """
    p_opening: float = 0.0

    def apply(
        self,
        u: Field2D,
        v: Field2D,
        mesh: Mesh2D,
        side: str,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Applies the opening boundary condition to the velocity field.

        At an opening, the velocity components are extrapolated from the
        interior using a zero-gradient assumption. This allows the flow
        to either enter or exit the domain freely.

        Args:
            u:      The x-velocity field (nx × ny).
            v:      The y-velocity field (nx × ny).
            mesh:   The computational mesh.
            side:   The side on which to apply the condition.

        Returns:
            A tuple (u, v) with the opening boundary values set.
        """
        u_arr: np.ndarray = u.data
        v_arr: np.ndarray = v.data

        # Zero-gradient extrapolation for velocity at an opening.
        # This is the same treatment as the zero-gradient outlet, but
        # the key difference lies in the pressure treatment.
        if side == "west":
            u_arr[0, :] = u_arr[1, :]
            v_arr[0, :] = v_arr[1, :]
        elif side == "east":
            u_arr[-1, :] = u_arr[-2, :]
            v_arr[-1, :] = v_arr[-2, :]
        elif side == "south":
            u_arr[:, 0] = u_arr[:, 1]
            v_arr[:, 0] = v_arr[:, 1]
        elif side == "north":
            u_arr[:, -1] = u_arr[:, -2]
            v_arr[:, -1] = v_arr[:, -2]
        else:
            raise ValueError(f"Invalid side: {side}")

        return u_arr, v_arr

    def apply_pressure(
        self,
        p: Field2D,
        mesh: Mesh2D,
        side: str,
    ) -> np.ndarray:
        """Applies the opening boundary condition to the pressure field.

        The key feature of the opening condition is that the pressure is
        prescribed (Dirichlet condition), unlike velocity which uses
        zero-gradient.

        Args:
            p:      The pressure field (nx × ny).
            mesh:   The computational mesh.
            side:   The side on which to apply the condition.

        Returns:
            The modified pressure field array with the prescribed pressure.
        """
        p_arr: np.ndarray = p.data

        # Prescribe the pressure at the opening boundary.
        # This is the distinguishing feature of the opening condition.
        if side == "west":
            p_arr[0, :] = self.p_opening
        elif side == "east":
            p_arr[-1, :] = self.p_opening
        elif side == "south":
            p_arr[:, 0] = self.p_opening
        elif side == "north":
            p_arr[:, -1] = self.p_opening
        else:
            raise ValueError(f"Invalid side: {side}")

        return p_arr


# ─── High-level application routine ────────────────────────────────────

def apply_boundary_conditions(
    u: Field2D,
    v: Field2D,
    p: Field2D,
    mesh: Mesh2D,
    bc_west: Optional[Union[Wall, Inlet, Outlet, SymmetryPlane, Periodic, Opening]] = None,
    bc_east: Optional[Union[Wall, Inlet, Outlet, SymmetryPlane, Periodic, Opening]] = None,
    bc_south: Optional[Union[Wall, Inlet, Outlet, SymmetryPlane, Periodic, Opening]] = None,
    bc_north: Optional[Union[Wall, Inlet, Outlet, SymmetryPlane, Periodic, Opening]] = None,
    u_old: Optional[Field2D] = None,
    v_old: Optional[Field2D] = None,
) -> dict[str, np.ndarray]:
    """High-level routine to apply boundary conditions on all four sides
    of the computational domain in a single call.

    This function serves as a convenient entry point for applying the
    complete set of boundary conditions. It iterates over all four domain
    sides and dispatches the appropriate `apply` and `apply_pressure`
    methods for each boundary condition object provided.

    It is crucial to understand that boundary conditions must be applied
    in a consistent order. Typically, inlet and wall conditions are applied
    first, followed by outlet, symmetry, and periodic conditions. This
    ordering ensures that no boundary condition overwrites another.

    Please note that if a side is not provided with a boundary condition,
    a no-slip wall condition is assumed by default. This conservative
    default ensures that the simulation will not run with undefined
    boundary conditions, even if it may not be the most appropriate choice.

    Args:
        u:           The x-velocity field (nx × ny).
        v:           The y-velocity field (nx × ny).
        p:           The pressure field (nx × ny).
        mesh:        The computational mesh.
        bc_west:     Boundary condition for the west side. Defaults to Wall(NO_SLIP).
        bc_east:     Boundary condition for the east side. Defaults to Wall(NO_SLIP).
        bc_south:    Boundary condition for the south side. Defaults to Wall(NO_SLIP).
        bc_north:    Boundary condition for the north side. Defaults to Wall(NO_SLIP).
        u_old:       Previous time step x-velocity (needed for CONVECTIVE outlet).
                     Defaults to None.
        v_old:       Previous time step y-velocity (needed for CONVECTIVE outlet).
                     Defaults to None.

    Returns:
        A dictionary containing the updated field arrays:
            {
                'u': u.data,
                'v': v.data,
                'p': p.data,
            }

    Raises:
        TypeError: If any of the provided boundary condition objects is
                   not an instance of the recognised boundary condition
                   classes.

    Example:
        >>> from boundary.conditions import (
        ...     Wall, Inlet, Outlet, SymmetryPlane,
        ...     Opening, Periodic, apply_boundary_conditions,
        ...     WallType, OutletType,
        ... )
        >>> from navier_stokes import Mesh2D, Field2D
        >>> mesh = Mesh2D(32, 32, lx=1.0, ly=1.0)
        >>> u = Field2D(32, 32)
        >>> v = Field2D(32, 32)
        >>> p = Field2D(32, 32)
        >>> result = apply_boundary_conditions(
        ...     u, v, p, mesh,
        ...     bc_west=Inlet(u_in=1.0),
        ...     bc_east=Outlet(outlet_type=OutletType.ZERO_GRADIENT),
        ...     bc_south=Wall(wall_type=WallType.NO_SLIP),
        ...     bc_north=SymmetryPlane(),
        ... )
    """
    # ── Compile the boundary condition configuration ───────────────────
    # Please note that None entries are replaced with the default no-slip
    # wall condition to ensure physical consistency.
    sides_config: list[tuple[str, Optional[Union[Wall, Inlet, Outlet, SymmetryPlane, Periodic, Opening]]]] = [
        ("west", bc_west),
        ("east", bc_east),
        ("south", bc_south),
        ("north", bc_north),
    ]

    # ── Apply conditions on each side ──────────────────────────────────
    # It is crucial to understand that the order of application matters.
    # We apply all four sides sequentially, and the last applied condition
    # for a given corner cell will take precedence.
    for side_name, bc_obj in sides_config:
        # Determine the boundary condition object to use.
        if bc_obj is None:
            # Default to no-slip wall if nothing is specified.
            bc_to_apply: Wall = Wall(wall_type=WallType.NO_SLIP)
        else:
            bc_to_apply = bc_obj

        # ── Apply the velocity boundary condition ──────────────────────
        # We check the type of the boundary condition object and call
        # the appropriate `apply` method.
        if isinstance(bc_to_apply, Outlet) and bc_to_apply.outlet_type == OutletType.CONVECTIVE:
            # Convective outlet needs previous time step velocity data.
            bc_to_apply.apply(u, v, mesh, side_name, u_old=u_old, v_old=v_old)
        else:
            # All other boundary condition types use the standard apply
            # method with just (u, v, mesh, side).
            bc_to_apply.apply(u, v, mesh, side_name)

        # ── Apply the pressure boundary condition ──────────────────────
        # Every boundary condition type has its own pressure treatment.
        bc_to_apply.apply_pressure(p, mesh, side_name)

    # ── Return the updated fields as a dictionary ──────────────────────
    return {
        "u": u.data,
        "v": v.data,
        "p": p.data,
    }
